title: "OnAgents.org"
description: "Exploring LLM Agent Systems with Dazza Greenwood"

# Build settings
markdown: kramdown

# Default layout for all pages
defaults:
  - 
    scope:
      path: "" # Applies to all files
    values:
      layout: default # Use our new default layout